# Generated by Django 4.2.4 on 2023-12-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_myreg_companyname_alter_myreg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreg',
            name='companyName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='myreg',
            table='job',
        ),
    ]
