# Generated by Django 4.2.4 on 2023-12-28 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_schedule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
