# Generated by Django 4.2.4 on 2023-12-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_delete_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/')),
            ],
        ),
    ]
