# Generated by Django 4.2.4 on 2023-12-29 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0006_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
