# Generated by Django 4.2.4 on 2023-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_delete_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myFile', models.FileField(upload_to='pdfs/')),
            ],
        ),
    ]
